AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Bundler/OrderedGems:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: False
